=== sebas-1106/lm_daw/2da_Eva/LenguajeMarcas/repasoXML_JSON/repaso2XML/config.dtd
<!ELEMENT configuracion (sitio_web+)>
    <!ELEMENT sitio_web (nombre, dominio, tecnologias_utilizadas, secciones, servidor+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dominio (#PCDATA)>
    <!ELEMENT tecnologias_utilizadas (tecnologia+)>
    <!ELEMENT secciones (seccion+)>
    <!ELEMENT seccion (#PCDATA)>
    <!ELEMENT servidor (puerto,bbdd+)> 
    <!ELEMENT puerto (#PCDATA)>
    <!ELEMENT bbdd (#PCDATA)>
    <!ELEMENT tecnologia (#PCDATA)>

=== sebas-1106/lm_daw/2da_Eva/LenguajeMarcas/repasoXML_JSON/repaso2XML/configuracion_web.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Validacion DTD en el propio fichero -->
<!-- <!DOCTYPE configuracion [
    <!ELEMENT configuracion (sitio_web+)>
    <!ELEMENT sitio_web (nombre, dominio, tecnologias_utilizadas, secciones, servidor+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dominio (#PCDATA)>
    <!ELEMENT tecnologias_utilizadas (tecnologia+)>
    <!ELEMENT secciones (seccion+)>
    <!ELEMENT seccion (#PCDATA)>
    <!ELEMENT servidor (puerto,bbdd+)> 
    <!ELEMENT puerto (#PCDATA)>
    <!ELEMENT bbdd (#PCDATA)>
    <!ELEMENT tecnologia (#PCDATA)>
]> -->
<!-- <!DOCTYPE configuracion SYSTEM "config.dtd"> -->
<!-- Enlazar con XSD estandar -->
<!-- <configuracion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="config.xsd"> -->
<!-- Enlazado con XSD con xml model -->
<?xml-model href="config.xsd"?>
<configuracion>
    <sitio_web>


        <nombre>Discoteca El Parcero</nombre>

        <dominio>www.discoteca.Elparcero.com</dominio>

        <tecnologias_utilizadas>
            <tecnologia>Angular</tecnologia>
            <tecnologia>Typescript</tecnologia>
            <tecnologia>GO</tecnologia>
        </tecnologias_utilizadas>

        <secciones>
            <seccion>Home</seccion>
            <seccion>News</seccion>
            <seccion>About</seccion>
        </secciones>
        
        <servidor>
            <puerto>3010</puerto>
            <bbdd>SQL Server</bbdd>
        </servidor>


    </sitio_web>
</configuracion>
